#!/usr/bin/env php
<?php

// set to run indefinitely if needed
set_time_limit(0);

/* Optional. It’s better to do it in the php.ini file */
date_default_timezone_set('America/Los_Angeles');

// include the composer autoloader
$autoload = require_once __DIR__.'/../vendor/autoload.php';

// import the Symfony Console Application
use Symfony\Component\Console\Application;

use NullDev\Skeleton\Command\UuidIdentityCommand;
use NullDev\Skeleton\Command\BroadwayCommandCliCommand;
use NullDev\Skeleton\Command\BroadwayEventCliCommand;
use NullDev\Skeleton\Path\Psr0Path;
use NullDev\Skeleton\Path\SpecPsr4Path;
use NullDev\Skeleton\Path\TestPsr4Path;
use NullDev\Skeleton\Path\Psr4Path;

$paths = [
    new Psr4Path(realpath(__DIR__.'/../src').'/', "NullDev\\Skeleton\\"),
    new SpecPsr4Path(realpath(__DIR__.'/../spec').'/', "spec\\NullDev\\Skeleton\\"),
    new TestPsr4Path(realpath(__DIR__.'/../tests').'/', "tests\\NullDev\\Skeleton\\"),
    new Psr0Path(realpath(__DIR__.'/../lib').'/', ""),
];

$uuidIdentityCommand = new UuidIdentityCommand();
$uuidIdentityCommand->setPaths($paths);
$uuidIdentityCommand->setAutoloader($autoload);

$broadwayCommandCliCommand = new BroadwayCommandCliCommand();
$broadwayCommandCliCommand->setPaths($paths);
$broadwayCommandCliCommand->setAutoloader($autoload);

$broadwayEventCliCommand = new BroadwayEventCliCommand();
$broadwayEventCliCommand->setPaths($paths);
$broadwayEventCliCommand->setAutoloader($autoload);

$app = new Application();
$app->add($uuidIdentityCommand);
$app->add($broadwayCommandCliCommand);
$app->add($broadwayEventCliCommand);
$app->run();

